name: Release

on:
  workflow_call:
    inputs:
      bump:
        required: true
        type: string
      preid:
        description: Pre-release identifier (e.g. alpha, beta, rc)
        required: false
        type: string
  default: ''
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write  # needed for OIDC token provenance
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          npm version ${{ inputs.bump }} ${{ inputs.preid && format('--preid={0}', inputs.preid) || '' }}
          npm publish --access public --provenance
          git push --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
