name: General Library CI/CD Workflow
# Shared by multiple projects

on:
  workflow_call:
    inputs:
      debug_mode:
        required: false
        type: boolean
        default: false
      workdir:
        required: false
        type: string
        default: "."
    secrets:
      pat_token:
        required: false

jobs:
  debug-print:
    uses: ./.github/workflows/debugger-reusable.yml
    with:
      debug_mode: ${{ inputs.debug_mode }}
      workdir: ${{ inputs.workdir }}
    secrets:
      pat_token: ${{ secrets.PAT_TOKEN }}

  notify-reviewers:
    if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
    uses: ./.github/workflows/automatically-add-reviewers.yml
    with:
      reviewers: 'chetasr,yuranich,olyasir,vigan-abd,u011,hakaari,natachikhinashvili,andretetherio,ignaciolarranaga'
    secrets: inherit
